import com.vanniktech.maven.publish.SonatypeHost
import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidLibrary)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.dokka)
    alias(libs.plugins.mavenPublish)
    alias(libs.plugins.androidxBaselineprofile)
    alias(libs.plugins.roborazzi)
}

group = System.getenv("GROUP") ?: project.findProperty("GROUP")?.toString() ?: "com.himanshoe"
version = System.getenv("VERSION_NAME") ?: project.findProperty("VERSION_NAME")?.toString() ?: "1.0.0-SNAPSHOT"

composeCompiler {
    metricsDestination.set(project.layout.buildDirectory.dir("compose_metrics"))
    reportsDestination.set(project.layout.buildDirectory.dir("compose_reports"))
}

kotlin {
    androidTarget {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
    }

    listOf(
        iosArm64(),
        iosSimulatorArm64(),
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "charty"
            isStatic = true
        }
    }

    jvm()

    js {
        browser()
    }

    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        browser()
    }

    sourceSets {
        androidMain.dependencies {
            implementation(compose.preview)
        }
        commonMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.ui)
            implementation(compose.components.resources)
            implementation(compose.components.uiToolingPreview)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.kotlinx.coroutinesTest)
        }
        getByName("androidUnitTest").dependencies {
            implementation(libs.robolectric)
            implementation(libs.junit4)
            implementation(libs.roborazzi)
            implementation(libs.roborazzi.compose)
        }
    }
}

android {
    namespace = "com.himanshoe.charty"
    compileSdk =
        libs.versions.android.compileSdk
            .get()
            .toInt()

    defaultConfig {
        minSdk =
            libs.versions.android.minSdk
                .get()
                .toInt()
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    testOptions {
        unitTests.isIncludeAndroidResources = true
    }
}

// Ship a baseline profile in the AAR so consuming apps get Charty's hot chart code AOT-compiled at
// install time. Generated by the :baselineprofile producer (which drives the :composeApp sample);
// the filter keeps only Charty's own classes out of the app-wide profile.
baselineProfile {
    filter { include("com.himanshoe.charty.**") }
}

dependencies {
    baselineProfile(projects.baselineprofile)
}

dokka {
    moduleName.set("charty")
    dokkaPublications.html {
        outputDirectory.set(layout.buildDirectory.dir("dokka/html"))
    }
}

// Task to generate verification.properties from template with environment variable
val generateVerificationFile by tasks.registering {
    val templateFile = file("src/commonMain/resources/META-INF/com/himanshoe/charty/verification.properties.template")
    val outputFile = file("src/commonMain/resources/META-INF/com/himanshoe/charty/verification.properties")
    val verificationToken = System.getenv("MAVEN_CENTRAL_VERIFICATION_TOKEN") ?: ""

    inputs.file(templateFile)
    inputs.property("verificationToken", verificationToken)
    outputs.file(outputFile)

    doLast {
        if (verificationToken.isEmpty()) {
            logger.warn("MAVEN_CENTRAL_VERIFICATION_TOKEN not set. Skipping verification file generation.")
            if (outputFile.exists()) {
                logger.info("Using existing verification.properties file.")
            }
        } else {
            outputFile.parentFile.mkdirs()
            val content = templateFile.readText().replace("\${MAVEN_CENTRAL_VERIFICATION_TOKEN}", verificationToken)
            outputFile.writeText(content)
            logger.lifecycle("✅ Generated verification.properties with token from environment variable")
        }
    }
}

tasks.withType<ProcessResources> {
    dependsOn(generateVerificationFile)
}

// The Compose-resources plugin's prepare/copy/convert tasks read `src/commonMain/resources`,
// which is where `generateVerificationFile` writes its output. They are not `ProcessResources`
// tasks, so without this explicit dependency Gradle 9's validation aborts (e.g. `allTests`) with an
// implicit-dependency error. Declaring the dependency is Gradle's recommended resolution.
tasks
    .matching { it.name.contains("ComposeResources") }
    .configureEach { dependsOn(generateVerificationFile) }

mavenPublishing {
    publishToMavenCentral(SonatypeHost.CENTRAL_PORTAL, automaticRelease = true)
    signAllPublications()

    pom {
        name.set("Charty")
        description.set("An Elementary Compose Multiplatform Chart library")
        inceptionYear.set("2025")
        url.set("https://github.com/hi-manshu/charty")

        licenses {
            license {
                name.set("The Apache Software License, Version 2.0")
                url.set("http://www.apache.org/licenses/LICENSE-2.0.txt")
                distribution.set("repo")
            }
        }

        developers {
            developer {
                id.set("hi-manshu")
                name.set("Himanshu Singh")
                url.set("https://github.com/hi-manshu")
            }
        }

        scm {
            url.set("https://github.com/hi-manshu/charty")
            connection.set("scm:git:git://github.com/hi-manshu/charty.git")
            developerConnection.set("scm:git:ssh://git@github.com/hi-manshu/charty.git")
        }
    }
}
