name: Pull Request Workflow

on: pull_request
jobs:
  code-style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: ktlint check
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ktlintCheck

